### ISSUE TITLE
dsPIC33 support

### ISSUE THREAD

**Issue by mrx23dot** [microchip-pic-avr-tools/pymcuprog#47]
Will it support this series in the future on MPLAB SNAP programmer?

The original MPLAP utility is really bad, and JAVA based.

**Comment by xedbg** [comment]
Hi @mrx23dot 
pymcuprog is a utility primarily for use with Microchip's CMSIS-DAP-based debuggers - this means AVR devices with UPDI.
In addition 8- and 16-bit Curiosity Nano boards are supported (since they use the same API).
Snap only supports AVR via this API, so generic dsPIC33 is not possible for pymcuprog.

**Comment by mrx23dot** [comment]
Thank you for the info!
Do you know about alternative SW for MPLAB SNAP programmer, even if it's not python?
